version: '3.8'

services:
  mysql:
    image: mysql
    container_name: market-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: market
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-market-data:/var/lib/mysql
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      timeout: 1s
      retries: 5
  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "33306:80"
    depends_on:
      mysql:
        condition: service_healthy
  grafana:
#    build: './config/grafana'
    image: grafana/grafana
    ports:
      - 3000:3000
#    volumes:
#      - /etc/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
#    networks:
#      monitoring:
#        aliases:
#          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#      - /etc/prometheus:/prometheus
#    networks:
#      monitoring:
#        aliases:
#          - prometheus
volumes:
  mysql-market-data:

#networks:
#  monitoring: